slots:
  disease:
    type: text
  symptom:
    type: text
  dept:
    type: text
  drug:
    type: text
  food:
    type: text
  sure:
    type: unfeaturized
  pre_disease:
    type: unfeaturized


intents:
  - first:
      triggers: action_first
  - greet
  - bye
  - affirmative
#  - search_disease
  - search_treat
  - search_food
  - search_symptom
  - search_cause
  - search_neopathy
  - search_drug
  - search_prevention
  - search_drug_func
  - search_disease_treat_time
  - search_easy_get
  - search_disease_dept
  - inform
  - request_professor_diagnosis

entities:
- disease
- symptom
- dept
- drug
- food

templates:
  utter_ask_symptom:
    - text: "请问你目前有哪些不适呢？"
    - text: "请问你有哪些症状呢"
    - text: "请告诉我当前有哪些症状吧"
  utter_ask_drug:
    - text: "请问你以前或者当前在服用什么药呢？"
    - text: "那你针对你的情况服用的什么药呢？"
    - text: "你既往服用的什么药呢"
  utter_ask_disease:
    - text: "请问你既往有什么病史呢"
    - text: "那你既往患过什么病呢"
  utter_first:
    - text: "您好，我是您的医疗助手Friende，我是个机器人，请问有什么可以帮您？"
  utter_greet:
    - text: "您好～"
    - text: "您好呀～"
  utter_goodbye:
    - text: "再见，祝您身体健康～"
    - text: "拜拜，希望我有帮到您～"
  utter_howcanhelp:
    - text: "您可以这样向我提问: 头痛怎么办/
                              什么人容易头痛/
                              头痛吃什么药/
                              头痛能治吗/
                              头痛属于什么科/
                              头孢地尼分散片用途/
                              如何防止头痛/
                              头痛要治多久/
                              糖尿病有什么并发症/
                              糖尿病有什么症状"
  utter_donknow:
    - text: "啊噢，我没有理解您说的话，我的理解力还需要更多的提升>_<。"

forms:
  - diagnosis_form


actions:
- utter_first
- utter_donknow
- action_first
- action_echo
- action_search_treat
- action_search_food
- action_search_symptom
- action_search_cause
- action_search_neopathy
- action_search_drug
- action_search_prevention
- action_search_drug_func
- action_search_disease_treat_time
- action_search_easy_get
- action_search_disease_dept
- utter_greet
- utter_howcanhelp
- utter_goodbye
- utter_ask_symptom
- utter_ask_drug
- utter_ask_disease